version: '3'

vars:
  SRC_DIRNAME: '{{.TASKFILE_DIR | osBase | replace "-" "_"}}'

tasks:
  default:
    deps:
    - task: generate-python-from-java
      vars:
        FILE: rpc_types.py


  generate-python-from-java:
    requires:
      vars: [FILE]
    vars:
      FILEPATH: src/{{.SRC_DIRNAME}}/{{.FILE}}
      GEN_PROG: gen/gen_{{.FILE}}
      JAVA_SOURCES: signal-cli/src/main/java/org/asamk/signal/json/*.java
    generates:
    - '{{.FILEPATH}}'
    sources:
    - '{{.GEN_PROG}}'
    - '{{.JAVA_SOURCES}}'
    cmds:
    - |
      cat {{.JAVA_SOURCES}} \
      | ast-grep scan --rule={{.RULE}} --stdin --update-all \
      | head -n-2 > {{.FILEPATH}}
    - ruff format {{.FILEPATH}}
