version: '3'

vars:
  PKG_NAME: signal_cli_jsonrpc

tasks:
  default:
    deps:
    - rpc_types
    - rpc_commands

  rpc_types: >
    python -m gen.gen_rpc_types
    > ${tmp:=$(mktemp -u)}
    && mv "$tmp" src/{{.PKG_NAME}}/rpc_types.py
  rpc_commands: >
    python -m gen.gen_rpc_commands
    > ${tmp:=$(mktemp -u)}
    && mv "$tmp" src/{{.PKG_NAME}}/rpc_commands.py
