version: '3'

vars:
  PKG_NAME: signal_cli_jsonrpc

tasks:
  default:
    deps:
    - gen_types
    - gen_commands

  check:
    cmds:
    - python -m gen.gen_types | git diff --no-index -w -- src/{{.PKG_NAME}}/types.py -
    - python -m gen.gen_commands | git diff --no-index -w -- src/{{.PKG_NAME}}/commands.py -

  gen_types: >
    python -m gen.gen_types > ${tmp:=$(mktemp -u)}
    && mv "$tmp" src/{{.PKG_NAME}}/types.py
  gen_commands: >
    python -m gen.gen_commands > ${tmp:=$(mktemp -u)}
    && mv "$tmp" src/{{.PKG_NAME}}/commands.py
